name: 'Run Unit Tests'
description: 'Runs unit tests on anaconda-opentelemetry package code'
inputs:
  python-version:
    description: 'Python version to use'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run tests with tox
      shell: bash
      run: tox -e py$(echo ${{ inputs.python-version }} | tr -d '.') -q