[tox]
envlist = py310,py311,py312,py313,py314

[testenv]
deps = -r requirements.txt
       pytest
       pytest-cov
       flask
setenv = OTEL_USE_CONSOLE_EXPORTER=TRUE
commands = pip install -qqq -e .
           pytest -s --cov=anaconda_opentelemetry --cov-report=term tests
