name: 'Run Integration Tests'
description: 'Runs unit tests on anaconda-opentelemetry package code'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
  otel-prod-token:
    description: 'OpenTelemetry production token'
    required: true
  otel-prod-endpoint:
    description: 'OpenTelemetry production endpoint'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run integration tests
      shell: bash
      env:
        ATEL_DEFAULT_AUTH_TOKEN: ${{ inputs.otel-prod-token }}
        ATEL_DEFAULT_ENDPOINT: ${{ inputs.otel-prod-endpoint }}
      run: python -m pytest tests/integration_tests/test_external_prod_otel.py