name: 'Run Integration Tests'
description: 'Runs unit tests on anaconda-opentelemetry package code'
inputs:
  python-version:
    description: 'Python version to use'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install flask

    - name: Run integration tests
      shell: bash
      run: python -m pytest tests/integration_tests/test_trace_carrier.py